# Generated by Django 5.2.4 on 2025-08-17 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mess_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='menu_photos/'),
        ),
        migrations.AddField(
            model_name='mess',
            name='address',
            field=models.TextField(default='Not provided'),
        ),
        migrations.AddField(
            model_name='mess',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='mess_photos/'),
        ),
        migrations.AddField(
            model_name='mess',
            name='pincode',
            field=models.CharField(default='000000', max_length=6),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
        migrations.AlterField(
            model_name='mess',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='mess',
            name='food_type',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='mess',
            name='location',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AlterField(
            model_name='mess',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
