# Generated by Django 5.2.4 on 2025-08-22 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mess_app', '0004_order_phone_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('COD', 'Cash on Delivery'), ('Online', 'Online Payment')], default='COD', max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Preparing', 'Preparing'), ('Out for Delivery', 'Out for Delivery'), ('Delivered', 'Delivered'), ('Rejected', 'Rejected')], default='Pending', max_length=20),
        ),
    ]
